version: "3.8"
services:
  peregrine:
    build: .
    ports:
      - "3033:80"
    environment:
      - VITE_API_URL=http://localhost:3001
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_MASTER_KEY=supersecretkey
    volumes:
      - /path/to/your/publicImages:/app/public/images
    depends_on:
      - meilisearch

  meilisearch:
    image: getmeili/meilisearch:v1.7
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    environment:
      - MEILI_MASTER_KEY=supersecretkey

volumes:
  meili_data:
  public_images:
